import { PhoneModel } from '@/types';

export const PHONE_MODELS: PhoneModel[] = [
  {
    id: 'iphone-15',
    brand: 'Apple',
    name: 'iPhone 15',
    displayName: 'iPhone 15',
    price: 499,
    canvasWidth: 360,
    canvasHeight: 720,
    frameColor: '#1a1a1a',
    popular: true,
  },
  {
    id: 'iphone-15-pro',
    brand: 'Apple',
    name: 'iPhone 15 Pro',
    displayName: 'iPhone 15 Pro',
    price: 549,
    canvasWidth: 370,
    canvasHeight: 740,
    frameColor: '#4a4a4a',
    popular: true,
  },
  {
    id: 'iphone-14',
    brand: 'Apple',
    name: 'iPhone 14',
    displayName: 'iPhone 14',
    price: 449,
    canvasWidth: 360,
    canvasHeight: 720,
    frameColor: '#1a1a1a',
  },
  {
    id: 'samsung-s24',
    brand: 'Samsung',
    name: 'Galaxy S24',
    displayName: 'Samsung Galaxy S24',
    price: 479,
    canvasWidth: 360,
    canvasHeight: 730,
    frameColor: '#2c2c2c',
    popular: true,
  },
  {
    id: 'samsung-s24-ultra',
    brand: 'Samsung',
    name: 'Galaxy S24 Ultra',
    displayName: 'Samsung Galaxy S24 Ultra',
    price: 549,
    canvasWidth: 390,
    canvasHeight: 800,
    frameColor: '#1c1c1c',
  },
  {
    id: 'samsung-s23',
    brand: 'Samsung',
    name: 'Galaxy S23',
    displayName: 'Samsung Galaxy S23',
    price: 429,
    canvasWidth: 360,
    canvasHeight: 720,
    frameColor: '#2c2c2c',
  },
  {
    id: 'pixel-8',
    brand: 'Google',
    name: 'Pixel 8',
    displayName: 'Google Pixel 8',
    price: 449,
    canvasWidth: 360,
    canvasHeight: 720,
    frameColor: '#3d3d3d',
  },
  {
    id: 'pixel-8-pro',
    brand: 'Google',
    name: 'Pixel 8 Pro',
    displayName: 'Google Pixel 8 Pro',
    price: 499,
    canvasWidth: 380,
    canvasHeight: 760,
    frameColor: '#2d2d2d',
  },
  {
    id: 'oneplus-12',
    brand: 'OnePlus',
    name: 'OnePlus 12',
    displayName: 'OnePlus 12',
    price: 429,
    canvasWidth: 370,
    canvasHeight: 740,
    frameColor: '#1a1a1a',
  },
  {
    id: 'nothing-phone-2',
    brand: 'Nothing',
    name: 'Phone (2)',
    displayName: 'Nothing Phone (2)',
    price: 449,
    canvasWidth: 365,
    canvasHeight: 730,
    frameColor: '#ffffff',
    popular: true,
  },
];

export const BRANDS = ['All', 'Apple', 'Samsung', 'Google', 'OnePlus', 'Nothing'];

export function getModelById(id: string): PhoneModel | undefined {
  return PHONE_MODELS.find((m) => m.id === id);
}
